<?php

return[
    [
        'employee_name' => 'Juan Dela Cruz',
        'position' => 'Administrative Aide VI',
        'office' => 'Treasurer\'s Office',
        'employment_status' => 'Permanent',
        'length_of_service' => '12 years',
        'civil_status' => 'Married',
        'sex' => 'Male',
        'age' => 42,
        'highest_educational_attainment' => 'Bachelor\'s Degree',
        'eligibility_type' => 'Career Service Professional',
        'eligibility_valid_until' => '2030-12-31',
        'citizenship' => 'Filipino',
        'pds_status' => 'Completed',
    ],
    [
        'employee_name' => 'Maria Clara Santos',
        'position' => 'Municipal Accountant',
        'office' => 'Accounting Office',
        'employment_status' => 'Coterminous',
        'length_of_service' => '5 years',
        'civil_status' => 'Single',
        'sex' => 'Female',
        'age' => 29,
        'highest_educational_attainment' => 'Master\'s Degree',
        'eligibility_type' => 'RA 1080',
        'eligibility_valid_until' => null,
        'citizenship' => 'Filipino',
        'pds_status' => 'For Review',
    ],
    [
        'employee_name' => 'Carlos Reyes',
        'position' => 'Utility Worker I',
        'office' => 'General Services Office',
        'employment_status' => 'Casual',
        'length_of_service' => '2 years',
        'civil_status' => 'Single',
        'sex' => 'Male',
        'age' => 24,
        'highest_educational_attainment' => 'High School Graduate',
        'eligibility_type' => 'None',
        'eligibility_valid_until' => null,
        'citizenship' => 'Filipino',
        'pds_status' => 'Incomplete',
    ],
    [
        'employee_name' => 'Ana Robles',
        'position' => 'HRMO II',
        'office' => 'Human Resource Management Office',
        'employment_status' => 'Permanent',
        'length_of_service' => '10 years',
        'civil_status' => 'Widowed',
        'sex' => 'Female',
        'age' => 39,
        'highest_educational_attainment' => 'Bachelor\'s Degree',
        'eligibility_type' => 'Career Service Sub-Professional',
        'eligibility_valid_until' => '2027-05-15',
        'citizenship' => 'Dual',
        'pds_status' => 'Completed',
    ],
    [
        'employee_name' => 'Mark Anthony Gomez',
        'position' => 'IT Officer I',
        'office' => 'MIS Office',
        'employment_status' => 'Contract of Service',
        'length_of_service' => '3 years',
        'civil_status' => 'Single',
        'sex' => 'Male',
        'age' => 27,
        'highest_educational_attainment' => 'Bachelor\'s Degree',
        'eligibility_type' => 'None',
        'eligibility_valid_until' => null,
        'citizenship' => 'Filipino',
        'pds_status' => 'Completed',
    ],
    [
        'employee_name' => 'Luisa Mae Villanueva',
        'position' => 'Nurse I',
        'office' => 'Health Office',
        'employment_status' => 'Permanent',
        'length_of_service' => '6 years',
        'civil_status' => 'Married',
        'sex' => 'Female',
        'age' => 33,
        'highest_educational_attainment' => 'Bachelor\'s Degree',
        'eligibility_type' => 'RA 1080',
        'eligibility_valid_until' => null,
        'citizenship' => 'Filipino',
        'pds_status' => 'Completed',
    ],
    [
        'employee_name' => 'Rafael Cruz',
        'position' => 'Driver II',
        'office' => 'Engineering Office',
        'employment_status' => 'Casual',
        'length_of_service' => '4 years',
        'civil_status' => 'Married',
        'sex' => 'Male',
        'age' => 38,
        'highest_educational_attainment' => 'Vocational Graduate',
        'eligibility_type' => 'Driver\'s License',
        'eligibility_valid_until' => '2026-09-15',
        'citizenship' => 'Filipino',
        'pds_status' => 'Incomplete',
    ],
    [
        'employee_name' => 'Karen Lim',
        'position' => 'Planning Officer II',
        'office' => 'Planning and Development Office',
        'employment_status' => 'Permanent',
        'length_of_service' => '7 years',
        'civil_status' => 'Single',
        'sex' => 'Female',
        'age' => 35,
        'highest_educational_attainment' => 'Master\'s Degree',
        'eligibility_type' => 'Career Service Professional',
        'eligibility_valid_until' => '2029-11-30',
        'citizenship' => 'Dual',
        'pds_status' => 'Completed',
    ],
    [
        'employee_name' => 'Emilio Buenaventura',
        'position' => 'Municipal Engineer',
        'office' => 'Engineering Office',
        'employment_status' => 'Permanent',
        'length_of_service' => '15 years',
        'civil_status' => 'Married',
        'sex' => 'Male',
        'age' => 48,
        'highest_educational_attainment' => 'Bachelor\'s Degree',
        'eligibility_type' => 'PRC - Licensed Civil Engineer',
        'eligibility_valid_until' => '2031-03-20',
        'citizenship' => 'Filipino',
        'pds_status' => 'Completed',
    ],
    [
        'employee_name' => 'Jasmine Reyes',
        'position' => 'Administrative Aide IV',
        'office' => 'Mayor\'s Office',
        'employment_status' => 'Contract of Service',
        'length_of_service' => '1 year',
        'civil_status' => 'Single',
        'sex' => 'Female',
        'age' => 23,
        'highest_educational_attainment' => 'Bachelor\'s Degree (Ongoing)',
        'eligibility_type' => 'None',
        'eligibility_valid_until' => null,
        'citizenship' => 'Filipino',
        'pds_status' => 'For Review',
    ],
];